/* PolarIS / 珍格格 — 项目问题清单（手写维护，截至 2026-08-19） */
window.ISSUE_META = {
  updated: "2026-08-19",
  sources: [
    "plan/exp_plan.md",
    "plan/4b_exp_plan.md",
    "scripts/setup/README.md",
    "scripts/train/experiments_v2/README.md",
    "vlm_exp/exp_result_mm.md",
    "scripts/eval/4b/AGENT_BENCH.md",
  ],
};

window.ISSUE_CATS = [
  { id: "all", label: "全部" },
  { id: "silent", label: "静默失败" },
  { id: "env", label: "环境 / CUDA" },
  { id: "signal", label: "训练信号" },
  { id: "runtime", label: "运行时" },
  { id: "eval", label: "评测链路" },
  { id: "science", label: "实验设计" },
];

window.ISSUE_STATUSES = [
  { id: "all", label: "全部状态" },
  { id: "live", label: "仍会踩" },
  { id: "ops", label: "运维未解" },
  { id: "partial", label: "部分兜底" },
  { id: "science", label: "科学债" },
  { id: "mitigated", label: "已兜底" },
];

window.ISSUES = [
  {
    id: "R1",
    title: "奖励配置被静默忽略",
    category: "silent",
    status: "mitigated",
    impact: "整条训练曲线作废",
    symptom: "E1 首跑 reward 卡在约 −0.98，\\boxed{} 几乎全判错。",
    cause: "verl-main 只认 reward.custom_reward_function.* 与 reward.reward_manager.*；旧顶层 custom_reward_function.path 会被丢掉，回退默认 math_dapo。",
    action: "必须用 reward.* 嵌套键 + scripts/reward_boxed.py。改配置后先看第一步 reward 是否离开 −1。",
  },
  {
    id: "R2",
    title: "DAPO Dynamic Sampling 是空实现",
    category: "silent",
    status: "science",
    impact: "v1 E2 不是完整 DAPO",
    symptom: "开了 +algorithm.filter_groups.enable=True，训练照跑、无报错。",
    cause: "verl 0.9.0.dev 只有 FilterGroupsConfig dataclass，v0 trainer 里没有实现。配置是静默 no-op。",
    action: "不要再把 filter_groups 当已上线能力。退化 group 靠离线难度池；真要 Dynamic Sampling 需自己实现或升级 verl。",
  },
  {
    id: "R3",
    title: "往训练环境装 agent 工具会挤掉 FLA",
    category: "silent",
    status: "live",
    impact: "GDN 悄悄变慢，不报错",
    symptom: "训练能跑，但 rollout/actor 明显变慢；vLLM 日志没有 Using Triton/FLA GDN prefill kernel。",
    cause: "在 verl_qwen35 里 pip 装 anthropic/openai/mcp 曾连带升级约 60 个包、挤掉 11 个，包括 flash-linear-attention 0.5.1。缺了只退回纯 torch。",
    action: "agent / MCP / Codex 另建 conda 环境。确认 FLA 用那行 kernel 日志，不要只看 import 成功。",
  },
  {
    id: "R4",
    title: "overlong 配错路径或 len=16K",
    category: "silent",
    status: "mitigated",
    impact: "从第 0 token 就开始罚长",
    symptom: "hydra 直接报错，或所有回复都被软惩罚、reward 系统性偏低。",
    cause: "字段在 reward.reward_kwargs.overlong_buffer_cfg，不是 reward.reward_manager.overlong_buffer；len 必须远小于 cap，旧值 16384=整条被罚。",
    action: "用 reward.reward_kwargs.*；16K 档 len=2048。看板看 critic/score/mean，不要用含惩罚的 rewards/mean。",
  },
  {
    id: "E1",
    title: "cuda_available=False 被误判成环境坏了",
    category: "env",
    status: "mitigated",
    impact: "空耗运维升驱动",
    symptom: "裸 python -c torch.cuda.is_available() 得到 False，报 NVIDIA driver too old (12040)。",
    cause: "torch/vLLM 是 CUDA 13 构建，pod 内核驱动只到 12.4。A100 靠 CUDA Forward Compatibility 用户态 libcuda，必须 source scripts/verl_env.sh。",
    action: "任何 CUDA 检查先 source verl_env.sh。不要据此要求把驱动升到 580。",
  },
  {
    id: "E2",
    title: "compat 包用 ar/tar 解开是残的",
    category: "env",
    status: "mitigated",
    impact: "PTX JIT 后期才爆，极难查",
    symptom: "cuda_available=True，基础 torch 能跑，但 triton/fla 内核莫名失败。",
    cause: "ar x + tar 解 cuda-compat 会截断 libnvidia-nvvm，并缺 libnvidia-ptxjitcompiler。",
    action: "只用 dpkg-deb -x。自检要同时看 libcuda.so.1 和 libnvidia-ptxjitcompiler.so.1。",
  },
  {
    id: "E3",
    title: "pip freeze 装不出可用环境",
    category: "env",
    status: "live",
    impact: "新机器 / 新 pod 复现失败",
    symptom: "按 envs/requirements_qwen35.txt 装完，CUDA 或 verl 仍不可用。",
    cause: "快照管不到 CUDA 13 compat 库，且 verl 是 editable 指向工作区。",
    action: "复现走 scripts/setup/setup_verl_qwen35.sh，快照只做版本对照。",
  },
  {
    id: "E4",
    title: "内网 PyPI 镜像没有 vllm 0.24.0",
    category: "env",
    status: "live",
    impact: "setup 在装 vLLM 处中断",
    symptom: "setup_verl_qwen35.sh 在 vllm==0.24.0 上报 No matching distribution。",
    cause: "mirror.in.zhihu.com 无 vllm；需要 extra-index-url=https://pypi.org/simple 并走代理。",
    action: "setup 脚本未固化该 fallback。新环境要手动加 extra-index 或改 setup。",
  },
  {
    id: "E5",
    title: "FLA TileLang / nvcc 与 PyTorch CUDA 头不一致",
    category: "env",
    status: "mitigated",
    impact: "4B 首次 actor backward JIT 失败",
    symptom: "CUDA compiler and CUDA toolkit headers are incompatible（nvcc 13.2 vs 头文件 13.0）。",
    cause: "FLA 自动选 TileLang。另一台 2B 机器用系统 nvcc 12.1，行为不同。",
    action: "统一 FLA_TILELANG=0，走 FLA 原生 Triton。A100 不受 Hopper 上 Triton 3.4+ 限制。",
  },
  {
    id: "E6",
    title: "vLLM custom all-reduce 在本机不可用",
    category: "env",
    status: "mitigated",
    impact: "4B TP=4 首次编译后直接挂",
    symptom: "custom_all_reduce.cuh:455 invalid argument。",
    cause: "CUDA forward-compat / NCCL 路径下 vLLM 自定义 all-reduce 不可用。",
    action: "统一 disable_custom_all_reduce=True，TP 走 NCCL。这是硬件兼容项，不是算法变量。",
  },
  {
    id: "E7",
    title: "flash-attn 装不上，旧 shim 文档已废",
    category: "env",
    status: "mitigated",
    impact: "按旧文档会卡在编译",
    symptom: "CUDA13/torch2.11 无预编译 wheel，源码编译失败。",
    cause: "verl 在 import flash_attn 失败时回退纯 torch pad/unpad，数值一致。",
    action: "不要装 flash-attn，也不要自建 shim。actor 用 sdpa，rollout 用 vLLM attention。",
  },
  {
    id: "E8",
    title: "Hydra 新增字段必须加 + 前缀",
    category: "env",
    status: "mitigated",
    impact: "配置阶段直接报错，或更糟的静默忽略",
    symptom: "filter_groups / gen_batch_size / reward_kwargs / enable_thinking 设了但 hydra 无法对 None 设子属性。",
    cause: "这些键默认不在 struct 里。recipe/ 目录为空，DAPO 也只能走 main_ppo。",
    action: "新增字段一律 +key=value。DAPO 走 main_ppo + reward.reward_manager.name=dapo，不要找 recipe/dapo。",
  },
  {
    id: "S1",
    title: "4B 上 easy_boxed 已经失效",
    category: "signal",
    status: "science",
    impact: "五算法挤在噪声里分不出",
    symptom: "4B Stage-1 zero-adv group 62–87%（几乎全对），名义 bs=32 实际只有 4–12 个 prompt 给梯度。",
    cause: "题对 4B 太简单，GRPO 组内优势恒为 0。",
    action: "v2 改用 [0.2, 0.8] 难度池。easy×4B in-band 只有 13.3%；扩池优先标 s1。",
  },
  {
    id: "S2",
    title: "16K 截断是没控住的混淆变量",
    category: "signal",
    status: "science",
    impact: "算法对比不干净",
    symptom: "2B 上 DAPO clip_ratio 2.25%，Dr.GRPO 15.82%（单步峰值 30.9%）。",
    cause: "v1 只有 DAPO 有 overlong 软惩罚，其余算法硬截断直接 −1，等于额外罚写长的算法。",
    action: "v2 全算法统一 shaped overlong。2B p95 仍超 16K（截断 10–16%），20K 应单因子消融，不要和 v2 混在一起。",
  },
  {
    id: "S3",
    title: "OPD 几乎为 0，PPO clip 从未工作",
    category: "signal",
    status: "science",
    impact: "算力全花在纯 on-policy 上",
    symptom: "actor/ppo_kl 0.7–3.4e-5，pg_clipfrac 0.002–0.074%，rollout/actor pearson > 0.9991。",
    cause: "ppo_mini_batch_size=16 / train_batch_size=32 只有 2 次内更新，第二次几乎不偏离第一次。",
    action: "v2 提高内更新次数，并跑 OPD 阶梯。熔断：clipfrac>15% 或 ppo_kl>1e-2。",
  },
  {
    id: "S4",
    title: "100K 思考模式预算不可行",
    category: "signal",
    status: "mitigated",
    impact: "原主实验方案已废弃",
    symptom: "烟测单 step rollout 解码 >14 分钟且长尾跑不完。",
    cause: "5 组 × 150 step 在 2 卡上会到数周～月。",
    action: "阶段一锁 16K 非思考；长 CoT 缩成阶段二单组 32K 验证。",
  },
  {
    id: "T1",
    title: "大词表 × 长序列 logits OOM",
    category: "runtime",
    status: "mitigated",
    impact: "actor update 直接炸显存",
    symptom: "entropy_from_logits 物化 [T, vocab=248320] 临时张量后 OOM。",
    cause: "Qwen3.5 词表极大，16K/32K 响应会撑爆。",
    action: "fused kernels + entropy chunking + entropy checkpointing，禁止物化完整 logits。",
  },
  {
    id: "T2",
    title: "多模态 Ray OOM + GPU 僵尸上下文",
    category: "runtime",
    status: "ops",
    impact: "M1 曾停在 130，双卡 lane 被锁死",
    symptom: "M1 在 105/136/131 反复 Ray node memory OOM；GPU0 残留约 74.9G、无 nvidia-smi PID、util=0。",
    cause: "OOM 后 CUDA context 未释放；无 root 不能 nvidia-smi --gpu-reset。未 checkpoint 步被丢弃。",
    action: "需要管理员 reset GPU0，或换空闲 2-GPU lane 恢复。不要让 pipeline 对着僵尸卡空转。后续 M1/M2/M3 已跑满 150，但僵尸卡模式仍可能复发。",
  },
  {
    id: "T3",
    title: "评测 pipeline 会空等已放弃的 checkpoint",
    category: "runtime",
    status: "ops",
    impact: "占着 supervisor、占着评测卡",
    symptom: "M1 正式放弃后，eval supervisor 仍每 5 分钟等 step150 actor。",
    cause: "训练失败/暂停与评测等待逻辑没有同一套完成标记。",
    action: "放弃某臂时同步停掉对应 supervisor，写 completion/abandon marker。",
  },
  {
    id: "V1",
    title: "tau-bench Judge 指向已下线 Ark 端点",
    category: "eval",
    status: "partial",
    impact: "agent 评测 404",
    symptom: "eval.sh 仍写 ep-20251014104513-lkxjb，Volcengine Ark 返回 404。",
    cause: "Judge / user-simulator 配置没随端点退役更新。",
    action: "部分队列已 fallback 到 zhihu gpt-5p5-apipro。根上应改 eval.sh，不要只在个别 launcher 打补丁。",
  },
  {
    id: "V2",
    title: "agent 评测 venv 在 /tmp 且缺依赖",
    category: "eval",
    status: "live",
    impact: "BFCL / tau 队列启动即挂",
    symptom: "verl_qwen35 缺 colorlog；/tmp/polaris_eval_agent_native_fc 重启后消失。",
    cause: "训练环境禁止装 agent 包（见 R3），评测又依赖临时 venv，没有持久化安装步骤。",
    action: "给 agent eval 单独、可复现的环境，不要依赖 /tmp。",
  },
  {
    id: "V3",
    title: "嵌套 K8s pod 跑不了 Docker agent bench",
    category: "eval",
    status: "ops",
    impact: "SWE / GAIA / Terminal-Bench 无法开跑",
    symptom: "docker pull 失败：failed to register layer: remount /, flags: 0x84000: permission denied。",
    cause: "当前 notebook pod 不能注册 Docker image layer，即使 vfs 也不行。",
    action: "换 privileged DinD、挂 host docker.sock，或 Terminal-Bench 走 modal/e2b/daytona。",
  },
  {
    id: "V4",
    title: "AIME 30 题区分不出 4B 算法差",
    category: "eval",
    status: "science",
    impact: "线下主辅判据错位",
    symptom: "题目层面标准误约 ±8pt，4B 五算法差异落在噪声内。",
    cause: "aime24/25 各 30 题；math_500 才是稳定主判据。",
    action: "算法排名以 math_500 为准；AIME 只看趋势。需要更稳的 agent/长任务评测另找机器。",
  },
  {
    id: "D1",
    title: "extend 实验回答不了「S1 冷启动」",
    category: "science",
    status: "science",
    impact: "容易把对照读过头",
    symptom: "easy@150 再训 vs 切 S1，看起来像数据对比。",
    cause: "B 臂是 easy 热身后切 S1，没有 DAPO×S1 从 step 0 的独立轨迹。",
    action: "只回答「150 之后换数据能否继续涨」。冷启动要另开实验。",
  },
  {
    id: "D2",
    title: "4B 难度池太小，只能靠重复 epoch",
    category: "science",
    status: "science",
    impact: "过拟合风险 vs 白跑 batch",
    symptom: "mix_4b_band 仅 2315 题，BS=64 时单 epoch 约 36 step。",
    cause: "easy_boxed×4B in-band 太少；s1 全量标注要数天 GPU。",
    action: "优先标 s1 扩池（pilot in-band 43%）。150 step 先保证步数到，再接受重复见题。",
  },
  {
    id: "D3",
    title: "单 seed × 150 step，训练曲线噪声大",
    category: "science",
    status: "science",
    impact: "不能用单步数值下结论",
    symptom: "pass rate 单步噪声约 ±10%。",
    cause: "每组 1 个 seed；E1 还没 pin data.seed。",
    action: "训练指标用末 20 步均值±标准差。math_500 才是第一判据。top-2 差 1pt 内再加 seed。",
  },
];
